src/styles/Avatar.scss, src/styles/Message.scss
Some selectors need to be extended because Angular and React handle components differently, Angular always adds a host element to the DOM tree when rendering a component, React doesn't have this functionality. This PR will contain the modifications from this week's sprint.
=> Add Angular specific selectors for Message and Avatar

src/styles/Thread.scss, src/styles/_base.scss
Add a `hideOnThread` class on the main panel (`Window` component) to correspond with the `Window` prop of the same name to handle the true value via CSS rather than in the component to prevent remounting of the list. Also, fixed the full class for `Thread` too correspond with the `fullWidth` prop there.
=> Window thread update

src/styles/_base.scss, src/styles/_variables.scss
Avoid performing HTTP requests to Google API to load fonts and use the system defaults instead. Developers should have possibility to choose their own fonts without performing redundant HTTP calls.
=> fix: replace font loading from google by the default system stack

src/styles/Attachment.scss
The sizing of the giphies can now be configured using the `giphyVersion` property. See https://github.com/GetStream/stream-chat-react/commit/0d97fc62d4e5f166162e1d375689196305fad420
@szuperaz - not sure if this will affect Angular.
=> Fix giphy sizing

src/styles/ChannelHeader.scss
Adjust styling of hamburger icon in the `ChannelHeader` according to changes in [stream-chat-react](https://github.com/GetStream/stream-chat-react/pull/1392):
- remove .str-chat__header-hamburger--line selector and associated rules
- add rules targeting `.str-chat__header-hamburger` and the child  svg
=> refactor: Adjust style of .str-chat__header-hamburger icon to target svg

src/styles/Attachment.scss, src/styles/Message.scss, src/styles/MessageInputFlat.scss, src/styles/Thread.scss
Fix visual bugs related to overflow in various message types.
fixes #67 
*Fixes: 1. Quoted message doesn't have the correct word-wrapping*
In MessageList:
In Thread:
*Note: Preview width has been set to 100% for better readability.*
*Fixes: 2. URL preview in thread overflows*
With OG image
Without OG image
*Fixes: 3. Video preview overflows*
*Fixes: 4. 
File upload preview in small message input overflows. The issue can be solved be reusing `MessageInputFlat` in the thread.
=> fix: word overflow in message an quoted message

src/styles/Message.scss, src/styles/MessageInput.scss
1. Provide a general css rule impacting all types of messages that would prevent messages' inner content to overflow from their message container.
2. Display the command list (Giphy) for message input above upload previews.
Message content overflowed in case of messages displaying uploaded file and in the past it was the case for the other message types too. Adding this rule should work for all the message types because the underlying problem is that the children of a flex container (`str-chat__message-simple`) have `min-width` value set by default to `auto`. This can make the block elements take up much more space than desired, resulting in overflow. Therefore the elements with class `str-chat__message-inner` get rule `min-width:0;`
Command list container got `z-index: 10001`. The system …
=> fix: Message overflow in thread & display command list above upload previews

src/styles/ActionsBox.scss, src/styles/ChannelList.scss, src/styles/ChannelSearch.scss, src/styles/Message.scss, src/styles/MessageInput.scss, src/styles/MessageInputFlat.scss, src/styles/Thread.scss, src/styles/_base.scss
Add missing dark theme styles to basic chat components. Allow to reuse those styles in website-react-examples demo apps.
=> fix: add missing dark theme styling for messaging app

src/styles/Message.scss
Error message display is broken both for React and Angular
Before fix:
React:
Angular:
After fix:
React:
Angular:
=> fix: Remove unnecessary margin from error messages

.gitignore, package.json, src-v2/styles/Avatar/Avatar-layout.scss, src-v2/styles/Avatar/Avatar-theme.scss, src-v2/styles/ChannelList/ChannelList-layout.scss, src-v2/styles/ChannelList/ChannelList-theme.scss, src-v2/styles/ChannelPreview/ChannelPreview-layout.scss, src-v2/styles/ChannelPreview/ChannelPreview-theme.scss, src-v2/styles/_theme-variables.scss, src-v2/styles/_utils.scss, src-v2/styles/index.layout.scss, src-v2/styles/index.scss
The aim of this PR is to showcase the new theming system (the channel list component is not fully redesigned, for example the loading screen, load more button are missing).
Integration with Angular + documentation: https://github.com/GetStream/stream-chat-angular/pull/275
=> feat: Theme v2 build process, channel list example

docs/theming/component-variables.mdx, src-v2/styles/Channel/Channel-layout.scss, src-v2/styles/Channel/Channel-theme.scss, src-v2/styles/ChannelHeader/ChannelHeader-layout.scss, src-v2/styles/ChannelHeader/ChannelHeader-theme.scss, src-v2/styles/ChannelList/ChannelList-layout.scss, src-v2/styles/ChannelList/ChannelList-theme.scss, src-v2/styles/ChannelPreview/ChannelPreview-layout.scss, src-v2/styles/ChannelPreview/ChannelPreview-theme.scss, src-v2/styles/MessageList/MessageList-layout.scss, src-v2/styles/MessageList/MessageList-theme.scss, src-v2/styles/Thread/Thread-layout.scss, src-v2/styles/Thread/Thread-theme.scss, src-v2/styles/_utils.scss, src-v2/styles/common/CircleFAButton/CircleFAButton-layout.scss, src-v2/styles/common/CircleFAButton/CircleFAButton-theme.scss, src-v2/styles/index.layout.scss, src-v2/styles/index.scss, src/styles/MessageNotification.scss, src/styles/Thread.scss
Components in this PR:
- Channel
- Channel header
- Thread header
- Thread
- Message list
- Jump to latest message
Responsive layout implemented in sample app, guide added to the [docs](https://github.com/GetStream/stream-chat-angular/pull/294/files#diff-99a4712356eb08af71235cafa9f1fe2615b9b8a718fd18f9b9cd3483ac792780) - maybe this could be a shared guide between React and Angular, I guess only the HTML snippets are framework-specific here
| Descripition | Figma | Implementation |
|-------------|--------|----------------|
| Channel header + jump to latest message button - light | <img width="417" alt="Screenshot 2022-05-20 at 16 37 43" src="https://user-images.githubusercontent.com/6690098/169551395-91b0fb15-fcff-4aae-8da6-a17ea6bfe7e2.png"> | <img width="946" alt="Screenshot 2022-05-20 …
=> Channel and header

src/styles/Thread.scss
Messages which content does not take the whole width should have the message options icons visible on hover without overflowing the parent message list container. This is a regression bug fix for https://github.com/GetStream/stream-chat-css/commit/d8d17300bfa50e399afb7c591808b6d11b795f9f
This fix does not solve the problem of message options overflow when the message content takes the whole width of the thread container.
Fixes:
Does not fix:
=> fix: remove 100% width on threads message inner component

src/styles/MessageList.scss
By giving the loading indicator's container absolute positioning, it can be removed from the flow of the messages in the `MessageList`. It also gets rid of the jumping while scrolling up and loading new messages, because now the `MessageList` height will not change until new messages are loaded.
=> feat: make loading indicator container float above the MessageList

src/v2/styles/Message/Message-layout.scss
=> fix: Long quoted message in message input

docs/theming/component-variables.mdx, src/v1/TypingIndicator.scss, src/v2/styles/TypingIndicator/TypingIndicator-layout.scss, src/v2/styles/TypingIndicator/TypingIndicator-theme.scss, src/v2/styles/index.layout.scss, src/v2/styles/index.scss
https://github.com/GetStream/stream-chat-angular/pull/315
closes #95
=> feat: Implement typing indicator theme-v2 #95

src/v1/MessageActions.scss, src/v1/Tooltip.scss, src/v1/_base.scss, src/v2/styles/MessageActionsBox/MessageActionsBox-layout.scss, src/v2/styles/Tooltip/Tooltip-layout.scss, src/v2/styles/_base.scss
Message actions context menu and tooltip components had a static position, which meant that they could easily overflow and not be properly visible. This is now fixed in Angular (both for theme-v1 and v2) this PR contains
- Rules for the dynamic positioning
- Turns off the static positioning in Angular
Angular changes: https://github.com/GetStream/stream-chat-angular/pull/317
React is not affected by this PR.
=> fix: Context menu and tooltip position in Angular (theme-v1 and v2)

src/v2/styles/Notification/MessageNotification-layout.scss, src/v2/styles/Notification/MessageNotification-theme.scss, src/v2/styles/index.layout.scss, src/v2/styles/index.scss
Angular and React have different notification handling. This PR consolidates the styles of the Angular notifications and the React "New messages" notificaion.
- The `MessageNotification` component had a few CSS rules that targeted the `str-chat__list-notifications` -> removed the ones that shouldn't be inside the `MessageNotification`
- Moved all notification CSS code inside the `Notification` folder
=> fix: Consolidate React and Angular notification styles

docs/theming/SDKSpecific.jsx
I didin't have this problem when locally running the docs, but in CI I got this error:
```
Error:  Docusaurus Node/SSR could not render static page with path /angular/theming/themingv2/ because of following error:
ReferenceError: window is not defined
at SDKSpecific (main:21[69](https://github.com/GetStream/stream-chat-angular/runs/7278758300?check_suite_focus=true#step:14:71)6:101)
at d (main:63582:498)
at bb (main:63585:16)
at a.b.render (main:63591:43)
at a.b.read (main:63590:83)
at Object.exports.renderToString (main:63601:138)
at doRender (main:14408:356)
at async serverEntry_render (main:14404:284)
[INFO] It looks like you are using code that should run on the client-side only.
To get around it, try using `<BrowserOnly>` (https://docusaurus.io/docs/docusaurus-core/#browseronly) or …
```
=> fix: Docusuarus CI error

src/v2/styles/MessageReactions/MessageReactions-layout.scss, src/v2/styles/MessageReactions/MessageReactionsSelector-layout.scss
This took me quite some time to figure out, but this should only be present in Angular SDK, but the `~@ctrl/ngx-emoji-mart/picker` stylesheets (imported by Angular SDK when the emoji selector button is added) conflict with styling in the message reactions.
=> fix: Emoji display in Angular

src/v2/styles/Message/Message-layout.scss, src/v2/styles/MessageReactions/MessageReactions-layout.scss, src/v2/styles/Tooltip/Tooltip-layout.scss
Extension of the [React Popper tooltip PR](https://github.com/GetStream/stream-chat-react/pull/1714). Removes unused tooltip styling.
=> ThemingV2: Popper tooltip

src/v2/styles/Autocomplete/Autocomplete-layout.scss
Add text-overflow rule to the text of suggestion list items.
=> fix: add text-overflow to suggestion list items

scripts/output.ts, scripts/parser.ts, src/v2/styles/AttachmentList/AttachmentList-layout.scss
- Include the scope of the CSS variables inside the docs
- If a CSS variable redefined on multiple scopes, list all values of the variable
- Scope information is automatically extracted during the generation process, no need to manually update these informations
=> feat: include scope info in docs, list values on all scopes

src/v1/Attachment.scss, src/v1/Message.scss, src/v1/MessageCommerce.scss, src/v1/Thread.scss, src/v1/VirtualMessage.scss
Fix the erratic scroll issue caused by vertical margins around messages in `VirtualizedMessageList`. Replace all message margins with padding in vertical axis. The goal is to keep the message spacing same:
1. in grouped and non-grouped setting (virtualized msg list)
2. between virtualized and non-virtualized message lists
3. taking into consideration messages with and without attachments
4. messages in main message list and in thread
Additionally the parent message alignment was fixed for virtualized thread.
Paddings and margins were combined around the messages and so the margin height was added to padding if it existed.
[adding_messages_VML.webm](https://user-images.githubusercontent.com/32706194/193301372-bc73e539-7729-4943-a065-01b39345c333.webm)
=> fix: replace vertical message margins with padding (theme v1)

src/v1/Audio.scss
Make the audio widget in theme v1 look the same for both virtualized and non-virtualized message list. In virtualized message list the widget was absolutely collapsed.
Override `font-size` of the audio title element.
<details><summary>bug</summary>
</details>
<details><summary>fixed</summary>
</details>
=> fix: fix collapsed audio widget in virtualized message list

src/v2/styles/Tooltip/Tooltip-layout.scss
Avoid popper tooltip from text from overflowing
**Bug**
**Fix**
=> fix: avoid popper tooltip text from overflowing

src/v1/ChannelList.scss, src/v1/ChannelSearch.scss, src/v2/styles/ChannelList/ChannelList-layout.scss, src/v2/styles/ChannelSearch/ChannelSearch-layout.scss, src/v2/styles/ChannelSearch/ChannelSearch-theme.scss
Change the scroll container from `str-chat__channel-list` to `str-chat__channel-list-messenger__main`. That would allow the infinite scroll component wrapping the actual channel preview listing to react to the scroll events.
Besides that, the channel search result list bugs are fixed both in theme v1 and v2.
Related to https://github.com/GetStream/stream-chat-react/pull/1803
**Channel search result list bugs (theme v1):**
<details><summary>Inline results</summary>
**Bug:**
**Fix:**
</details>
<details><summary>Popup results</summary>
**Bug:**
**Fix:**
</details>
**Channel search result list bugs (theme v2):**
<details><summary>Popup results</summary>
**Bug (the results are not floating above the channel list):**
**Fix:**
</details>
=> feat: adapt channel list for infinite scroll (React only)

src/v1/Card.scss, src/v1/ChannelHeader.scss, src/v1/MessageInput.scss, src/v1/TypingIndicator.scss, src/v1/_variables.scss
fixes: https://github.com/GetStream/stream-chat-react/issues/1886
Put the value `-1` in calc expression first.
For more, see: https://github.com/postcss/postcss-calc/issues/142
=> fix: prevent postcss parse syntax error

src/v2/styles/Avatar/Avatar-layout.scss, src/v2/styles/Avatar/Avatar-theme.scss, src/v2/styles/_global-theme-variables.scss
For the messenger clone sample app, the online indicator is an important feature (you might not want to call someone if they are offline), so I added it to the Angular chat SDK.
The changes only affect the Angular SDK, I tested with the React typescript app, and didn't spot a problem there.
For Angular:
=> feat: Online indicator for Angular

src/v2/styles/MessageList/MessageList-layout.scss
Add padding to the first message in the message list to solve the problem where reactions aren't properly visible. Tested with Angular and React SDK.
Only added this to the message list. I wasn't sure if the changing height of the messages wouldn't cause problems inside the virtualized list.
Before:
After:
=> fix: Add padding to first message in message list

src/v2/styles/_emoji-replacement.scss, src/v2/styles/index.layout.scss
Fix: https://github.com/GetStream/stream-chat-react/issues/1944
Provide replacement for emoji flags in Windows for theming v2. This feature was supported in theming v1, but was not ported to v2.
=> fix: add support for flag emoji replacements for Windows in theming v2

src/v2/styles/TypingIndicator/TypingIndicator-layout.scss
At least align the TypingIndicator to the bottom in the VirtualizedMessageList
Unfortunately the `TypingIndicator` is part of the scrolled list and so if the user scrolls up, the indicator is not visible. However, moving the `TypingIndicator` component out of the VML above `MessageListNotifications` would be a breaking change.
Partially fixes: https://github.com/GetStream/stream-chat-react/issues/1951
Before
After
=> fix: position the TypingIndicator at the bottom of the VirtualizedMessageList

src/v2/styles/Channel/Channel-layout.scss, src/v2/styles/Thread/Thread-layout.scss
Support `-hideOnThread` flag in stylesheet v2 for `stream-chat-react`. When `str-chat__main-panel--hideOnThread` class is present, the main message list should not be displayed and the thread panel should occupy the vacated space.
fix: https://github.com/GetStream/stream-chat-react/issues/2024
=> fix(react-sdk): hide main panel on hideOnThread in stylesheet v2

src/v1/Card.scss
Fix the visual bug of overflowing giphy preview. The message action buttons were not visible and shuffling was not possible.
These changes apply only to CSS v1 in VirtualizedMessageList only in stream-chat-react.
**Before (missing message actions)**
**After (fixing also image fit)**
=> fix: prevent giphy in preview from overflowing in virtualized message list

src/v2/styles/MessageList/MessageList-layout.scss
We have a hacky solution for applying `padding-top` to the first message in the list, this is to fix the issue of reactions not displayed properly for the first message. This hack is not necessary if we have a date separator, so this PR turns that of for that cases.
=> feat: Don't apply padding-top hack when date separator is in use

src/v2/styles/MessageList/MessageList-layout.scss
=> fix: Padding of first message on date separator

src/v2/styles/ChannelSearch/ChannelSearch-layout.scss
If the search results overflew the container, it was not possible to scroll them. The adjustments are done to both the inline and popup version of search results. The search bar height is now fixed to match with the absolute popup positioning.
=> fix: make search results scrollable

src/v2/styles/vendor/react-image-gallery.scss, src/vendor/react-image-gallery.scss
Package `react-image-gallery` [updated class names](https://github.com/xiaolin/react-image-gallery/pull/692) (released in `1.2.12` as minor version update) it uses internally which in turn broke our gallery component due to the fact that we use [their updated style sheet](https://github.com/GetStream/stream-chat-css/blob/develop/src/v2/styles/vendor/react-image-gallery.scss).
Our package `stream-chat-react` specifies `react-image-gallery` version in `package.json` as `^1.2.7` which means that package managers will install any available version up to `>2.0.0`. Our modified vendor stylesheet works with versions only up to `>1.2.12` which in turn breaks applications which install newer versions of the `react-image-gallery`.
=> fix(react-image-gallery): adjust react-image-gallery class names

src/v2/styles/ChannelSearch/ChannelSearch-layout.scss
Avoid conflicts with integrators' custom rules attached to `inline` class.
=> fix: namespace the ChannelSearch's root element "inline" and "popup" classes

src/v1/MessageInput.scss, src/v2/styles/Autocomplete/Autocomplete-layout.scss
=> fix: class name for Angular slash commands hiding

src/v2/styles/Autocomplete/Autocomplete-layout.scss, src/v2/styles/ChannelHeader/ChannelHeader-layout.scss, src/v2/styles/ChannelPreview/ChannelPreview-layout.scss, src/v2/styles/ChannelSearch/ChannelSearch-layout.scss, src/v2/styles/Message/Message-layout.scss, src/v2/styles/Thread/Thread-layout.scss, src/v2/styles/Tooltip/Tooltip-layout.scss, src/v2/styles/_utils.scss
=> fix: prevent glitch text from overflowing elements

src/v2/styles/AttachmentPreviewList/AttachmentPreviewList-layout.scss
Fix file preview error overlay position:
=> fix: file attachment preview error overlay

.releaserc.json, package.json
The separate v3 release branch is needed to avoid introducing breaking changes to stream-chat-react release-v10
=> chore: setup semantic-release for releases from v3

src/v2/styles/vendor/react-image-gallery.scss
Related to: https://github.com/GetStream/stream-chat-react/issues/2210
The stream-chat-react SDK will use `BaseImage` component to display images and image fallbacks.
This change affects only stream-chat-react.
=> feat(stream-chat-react): add styles for BaseImage to react-image-gallery stylesheet

src/v2/styles/AttachmentList/AttachmentList-layout.scss, src/v2/styles/vendor/react-image-gallery.scss
Content was pushed to the top of the viewport when in fullscreen mode.
This change affects only stream-chat-react.
=> fix(stream-chat-react): position image gallery content fullscreen

src/v2/styles/AttachmentList/AttachmentList-layout.scss
Fixes: https://github.com/GetStream/stream-chat-react/issues/2209
=> fix: position image download icon relative to the image fallback button

src/v2/styles/MessageReactions/MessageReactions-layout.scss, src/v2/styles/MessageReactions/MessageReactions-theme.scss
Display all reacting users for message reactions (not just the latest 10) in Angular SDK
The tooltip was replaced with a modal window for Angular
New reactions details UI:
=> feat(angular): display all reacting users for message reactions

src/v2/styles/Message/Message-layout.scss, src/v2/styles/Message/Message-theme.scss
With the new Angular reaction details UI it took two clicks on mobile to open the reactions (first was to open message options, second to open the modal). To fix that clicking on a reaction icon won't open the message options.
It uses the new `:has` selector which doesn't yet have [complete browser support](https://caniuse.com/?search=%3Ahas) so we use the [`@supports` syntax ](https://caniuse.com/?search=%40supports) to only use the selector in browsers that support it. For other browsers the users will have to click twice to open the message reactions.
⚠️ Autoprefixer might need to be updated in older applications that use the React/Angular SDK: https://getstream.slack.com/archives/C06CF5TKRGA/p1704989315231429
The message options not displayed when hovering over a reaction icon:
React …
=> fix: double click is required for opening reaction details

src/v2/styles/MessageReactions/MessageReactions-layout.scss
We're updating UI for displaying reactions. Instead of showing the latest reactions only, we're adding a separate modal window full the full list of reactions.
React SDK renders emoji as block elements, so some additional styling was required. BTW, that means that [inline styling](https://github.com/GetStream/stream-chat-angular/blob/1ab3e26a3d89df85d6973c420529d52873186923/projects/stream-chat-angular/src/lib/message-reactions/message-reactions.component.ts#L27) can be removed in Angular SDK (cc @szuperaz).
=> feat: update styles for reactions modal

src/v2/styles/MessageBounceOptions/MessageBounceOptions-layout.scss, src/v2/styles/MessageBounceOptions/MessageBounceOptions-theme.scss, src/v2/styles/index.layout.scss, src/v2/styles/index.scss
`MessageBounceOptions` refers to the contents of a modal dialog displayed when clicking on a message that bounced because of moderation rules.
This is a simple dialog with three buttons. Buttons are customizable via standard component overrides.
=> feat: add message bounce options styles

src/v2/styles/MessageReactions/MessageReactions-layout.scss
This PR affects both Angular and React
This is an old bug, but we probably didn't notice it because it requires lots of reactions + very narrow device: but the reaction list above the message bubble could overflow. 
This PR adds scrolling to the reaction list
A room for improvement: the reaction list could fill the whole width of the message list (see screenshots for visual explanation), this is currently not happening due to our CSS/HTML structure. Since this is not an easy fix, I'll leave this to our future selves.
Before:
After:
=> fix: reaction list is now scrollable

src/v2/styles/Autocomplete/Autocomplete-layout.scss
Angular-only change: the mention autocomplete menu could overflow before
=> fix(angular): Mention autocomplete can overflow

src/v2/styles/MessageBouncePrompt/MessageBouncePrompt-layout.scss, src/v2/styles/MessageBouncePrompt/MessageBouncePrompt-theme.scss, src/v2/styles/index.layout.scss, src/v2/styles/index.scss
🚂 #264 
We've picked a better name for ~`MessageBounceOptions`~ `MessageBouncePrompt`, but that means we have to rename our css classes as well.
The feature has not been released yet, so not a breaking change :)
=> feat: rename MessageBounceOptions ➡️ MessageBouncePrompt

src/v2/styles/MessageReactions/MessageReactions-layout.scss
We got reports of layout shifts when opening the reactions modal. This PR fixes them.
There were two reasons for the layout shifts:
1. Mismatch between fallback emoji size and sprite emoji size. Fixed by providing an ability to customize sprite emoji size using a CSS variable, and setting sprite emoji size to equal font size.
2. A quick flash of the loading state inside the modal. Fixed by setting minimum height for the modal, so that in most cases it will have the same height during and after loading.
https://github.com/GetStream/stream-chat-css/assets/975978/fdff3785-6674-4cf2-a1f3-678bfb319a09
=> fix: prevent layout shifts in reactions modal

src/v2/styles/Message/Message-layout.scss, src/v2/styles/_utils.scss
Currently message actions are only displayed on hover, and are not accessible from keyboard. This PR makes message actions more accessible.
1. Message actions are now displayed when the message is focused
2. Action buttons now have outline to clearly show focus
This PR includes a slightly scary change to the `button-reset` mixin. Previously it removed outline. However, having outline for focused items is important for accessibility, so now outline is not removed.
https://github.com/GetStream/stream-chat-css/assets/975978/7824625d-5ba0-4ba1-b4b5-1572194e33ac
=> fix: make message actions keyboard accessible

src/v2/styles/AttachmentList/AttachmentList-layout.scss, src/v2/styles/Message/Message-layout.scss
This is an Angular-only change
=> fix(angular): move inline style attributes to CSS files

src/v2/styles/Message/Message-layout.scss
Adds styles for a new collapsible section in message status that shows the last time message text was updated.
https://github.com/GetStream/stream-chat-css/assets/975978/efb1e985-3d67-4ba2-9b72-7522d76c8315
=> feat: add message edited timestamp

src/v2/styles/AttachmentList/AttachmentList-layout.scss
I think we only need this for older SCSS versions (like the one used in Angular 12 apps)
`$min_amplitude_height` is wrapped with `#{}` when used in `calc` expressions
=> fix: syntax for $min_amplitude_height

src/v2/styles/ImageCarousel/ImageCarousel-layout.scss, src/v2/styles/ImageCarousel/ImageCarousel-theme.scss
This is an Angular-only change, React uses a different UI for image modals.
On the Angular SDK the images in the attachment modal were quite small. There were two reasons for this:
- The layout was built in a way that didn't maximize space for images
- We didn't have a responsive layout to make the modal bigger on mobile devices -> we generally don't provide different layouts on different devices, but I think this is one of the few places where it makes sense to add a media rule
Before:
After:
=> fix(angular): make images bigger in image modal

src/v2/styles/AttachmentList/AttachmentList-layout.scss
The wavebar container for voice recording had a fixed width of `120px` but it's very easy to create a layout (using our CSS variables) where it caused an overflow. This PR sets a responsive width for the wavebar.
- The wavebar container doesn't have a fix size anymore
- The wavebars still have a fixed width
- The React SDK uses a fixed a sample size (40) so it will always create a wavebar that's 120px wide (no UI change there)
- The Angular SDK uses the `--str-chat__voice-recording-amplitude-bar-width` and `--str-chat__voice-recording-amplitude-bar-gap-width` variables to compute the sample size that fits the wavebar container
My first implementation was to set `width: auto` to the individual wavebars and then there is no need to compute anything in the SDK, but the problem is that this …
=> fix: make wavebar data responsive

src/v2/styles/AttachmentList/AttachmentList-layout.scss, src/v2/styles/AttachmentList/AttachmentList-theme.scss
- Add error message to voice recording
- Add download icon to voice recording -> Angular will be released without downloading (there are some issues downloading memos from Android and RN) but I pushed the markup if the issues are fixed, we can just easily turn this on
- Adjust angular template for file attachments -> previously clicking anywhere in the attachment markup downloaded the file, now only clicking on the file name or download icon will cause download
This is currently Angular-only, React can follow with implementation
Markup with error message + download icon
Since we have some problems with downloads, the released markup in the Angular SDK won't feature a link to download the voice memo:
Make sure to test with both Angular and React (with both `MessageList` and …
=> feat: add error message and download icon to voice recordings

src/v2/styles/_global-theme-variables.scss
Some letter are cut-off
- I've updated all `line-height` values to be unitless
- I made sure we use at least `1.2` everywhere
Context: https://getstream.slack.com/archives/C06CF5TKRGA/p1712156840771619
=> fix: some letter are cut-off

src/v2/styles/ChannelPreview/ChannelPreview-layout.scss
Affects both Angular and React
Context: https://getstream.slack.com/archives/C06CF5TKRGA/p1712244144318319?thread_ts=1712156840.771619&cid=C06CF5TKRGA
Before:
After:
=> fix: new message indicator

src/v2/styles/ChannelPreview/ChannelPreview-layout.scss, src/v2/styles/ChannelPreview/ChannelPreview-theme.scss
A customer was asking for this on Angular. The PR only affects Angular.
Figma: https://www.figma.com/file/ekifwChR9tR7zRJg1QEzSM/Chat-UI-Kit-1.0-All-platforms?type=design&node-id=26955-59584&mode=design&t=8HmnWEBt1LkPvuOX-0 
=> feat(angular): add message status and time to channel preview

src/v2/styles/AttachmentList/AttachmentList-layout.scss, src/v2/styles/Message/Message-layout.scss
We use `flex-start` in the CSS codebase, these two were just a mistake I guess, but they're causing warning from autoprefixer ("autoprefixer: start value has mixed support, consider using flex-start instead")
=> fix: use flex-start instead of start

doc-templates/component-variables.template.mdx, doc-templates/global-variables.template.mdx, doc-templates/palette-variables.template.mdx, docs/theming/introduction.mdx
The Angular SDK is about to remove support for theme-v1, so any reference to that is removed from the docs. Since stream-chat-angular v4 and v5 are maintained in parallel the CSS docs feature code snippets for both versions.
React docs is unchanged.
=> feat(angular): remove theme-v1 from Angular SDK

src/v2/styles/_base.scss
Fix this issue: https://github.com/GetStream/stream-chat-angular/issues/603
The `font-family` setting is inherited, so there is no need for the extra ` *` selector, which can make integrators' lives harder.
=> fix: remove unnecessary selector specificity from font-family setting

src/v2/styles/AttachmentList/AttachmentList-layout.scss, src/v2/styles/AttachmentList/AttachmentList-theme.scss, src/v2/styles/AttachmentPreviewList/AttachmentPreviewList-layout.scss, src/v2/styles/AttachmentPreviewList/AttachmentPreviewList-theme.scss
Add styles for unsupported message attachment
Related to https://github.com/GetStream/stream-chat-react/pull/2383
Unknown attachments are by default rendered as follows:
1. Message attachment in a message list:
2. Message attachment preview in message composer
=> feat: add styles for unsupported message attachment

src/v2/styles/_emoji-replacement.scss, src/v2/styles/_icons.scss, src/v2/styles/_variables.scss
If an integrator does a custom style bundling (instead of importing the `index.scss`) they might need to set a custom asset path
=> fix: allow configuring asset path for icons

src/v2/styles/EditMessageForm/EditMessageForm-theme.scss
=> docs: Update edit message modal docs

src/v2/styles/Autocomplete/Autocomplete-layout.scss
Make sure the autocomplete suggestion list is always above the textarea.
Before:
After:
=> fix: adjust MessageInput Autocomplete position above textarea with multiple rows

src/v2/styles/Channel/Channel-layout.scss, src/v2/styles/Thread/Thread-layout.scss
The rule applied only to React component Window, from which it has been removed.
=> feat: remove str-chat__main-panel--hideOnThread rules

src/v2/styles/LoadingIndicator/LoadingIndicator-layout.scss
Previously the Angular SDK only displayed a loading indicator at the top of the message list (loading older messages). 
However, the new virtualized message list removes DOM nodes when the user scrolls to the very top or bottom of the current message list, causing a short pause in the scrolling (the virtualized message list inside the Angular SDK is a simpler version than what you have in React, it doesn't track the height of each message, that's why it can only remove DOM nodes when the user reaches the very top/bottom of the currently displayed list).
This means that if the user scrolls up a lot, then down a lot, the virtualized list will change the displayed messages when the user scrolls to the bottom of the current message list, this happens very fast, but still, without a loading …
=> fix(angular): bottom loading indicator

src/v2/styles/ThreadList/ThreadList-layout.scss
=> fix(ThreadListItem): add text overflow for long user names

src/v2/styles/MessageActionsBox/MessageActionsBox-theme.scss, src/v2/styles/MessageReactions/MessageReactionsSelector-theme.scss
On touch devices, you don't need special styles for hover action. However, mobile OS-es still handle the `:hover` CSS selector, but it can be confusing to the user when they accidentally activate the `:hover` selector, this PR removes the `:hover` styles for touch devices inside the message menu.
=> fix: remove hover styles for touch devices inside the message menu

src/v2/styles/Dialog/Dialog-layout.scss, src/v2/styles/Message/Message-layout.scss, src/v2/styles/MessageReactions/MessageReactionsSelector-layout.scss, src/v2/styles/index.layout.scss
Supports https://github.com/GetStream/stream-chat-react/pull/2489
`ReactionSelector` is positioned by popperjs so cannot be positioned absolutely. `MessageActionsBox` and `ReactionSelector` are positioned above a transparent overlay.
=> feat: add styles to support dialog display in stream-chat-react

src/v2/styles/AttachmentPreviewList/AttachmentPreviewList-layout.scss
This PR affects both Angular and React (I tested with the React vite example app).
Issue: the delete and retry icons had higher z-index than the channel list menu, causing a visual glitch
=> fix: z-index inside attachment preview

src/v2/styles/Message/Message-layout.scss
- White spaces were treated differently in quoted messages
- Adds clamping to quoted message
See screenshot for details
Merge this if you want the fix for React as well: https://github.com/GetStream/stream-chat-react/pull/2601
**White space incosistencies**
If we quoted a message with line-breaks before...
...the line breaks were not properly preserved in the quote preview:
**Clamping**
Without message clamping quoted messages can take up a lot of space:
With message clamping:
=> fix: white space inconsistency in quoted messages, clamp quoted messages

src/v2/styles/Message/Message-layout.scss
Applies to React SDK only. The SDK displays the message actions dialog over an overlay. Once the overlay is displayed, the message hover styles are removed. Other users' messages that are not hovered over are applied margin on inline-end as a placeholder for message options. This PR fixes the state, when rendering the said overlay leads the message options being displayed with margin on inline-end. In narrow layouts this leads to message component jumping.
Fixes REACT-268
=> fix: add margin only to other users' messages without open actions dialog

src/v2/styles/Message/Message-theme.scss
Adjust styling of the mention span element so it gets picked up within message, quoted message and quoted message within message input.
Before:
After:
=> fix: move mention styling outside message

src/v2/styles/Message/Message-layout.scss
Tabbing through messages avoided focusing message options if the message had reactions.
fixes REACT-388
**Incorrect tabbing**
On the way back the options are not focused on message with reaction
[incorrect-tabbing.webm](https://github.com/user-attachments/assets/5a80f36d-2108-4a7f-b97c-e8c91b05dfea)
**Corect tabbing**
On the way back the options are focused on message with reaction
[correct-tabbing.webm](https://github.com/user-attachments/assets/a15f5e48-c13f-44c5-ab2f-70d5d11a28b4)
=> fix: enable focus through message options when message reactions are displayed

src/v2/styles/Message/Message-layout.scss, src/v2/styles/Message/Message-theme.scss, src/v2/styles/MessageActionsBox/MessageActionsBox-theme.scss
Add styles to 
- display message reminders 
- display message actions submenu with message reminder actions
[yMzp.webm](https://github.com/user-attachments/assets/01ef3565-b068-4d3e-9599-6bd5a685720d)
=> feat: add message reminder styles

src/v2/styles/Modal/Modal-theme.scss, src/v2/styles/Poll/Poll-layout.scss, src/v2/styles/Poll/Poll-theme.scss
Adjust selectors so that they target modal content rendered outside the original parents (due to rendering via React portal). The original selectors are kept to keep backwards compatibility.
=> feat: adapt styles for modal rendered at the top of the chat component tree

src/v2/styles/Message/Message-layout.scss, src/v2/styles/Message/Message-theme.scss
Add styles for delivered and sent message statuses (need to be smaller than the avatar)
None
=> feat: add styles for delivery receipts
