GetStream/stream-chat-css

src/styles/MessageNotification.scss

Added scroll to the bottom and unread messages indicator based on these designs: https://www.figma.com/file/ekifwChR9tR7zRJg1QEzSM/Chat-Sample-App?node-id=16156%3A276564, https://www.figma.com/file/ekifwChR9tR7zRJg1QEzSM/Chat-Sample-App?node-id=12046%3A496

Add scroll to bottom and unread indicator

---

src/styles/MessageInputFlat.scss

This only affects the Angular SDK, the React SDK this from code

feat: Show send button if input has attachments

---

.github/workflows/release.yml
package.json

chore: Implement automatic semantic release

---

src/styles/SendButton.scss
src/styles/SmallMessageInput.scss

SendButton component includes className: upload-previews-displayed if numberOfUploads. See: https://github.com/GetStream/stream-chat-react/pull/1352

fix: fixes react sdk issue 1349

---

src/styles/SmallMessageInput.scss

Found a UI mistake in the last round of testing

fix: Emoji picker in Angular when sending attachments in threads

---

src/styles/MessageInputFlat.scss
src/styles/SmallMessageInput.scss

The React and Angular HTML tree is a bit different so I needed to add some CSS rules that only apply to the Angular SDK

feat: Implement slow mode in Angular SDK

---

src/styles/_variables.scss

1. remove overriding css variables `--white`, `--black`, `--grey`
2. replace unused value of `$grey` scss var by the value in the last overriding css var  `--grey`

refactor: remove duplicate css variables

---

src/styles/ChannelHeader.scss
src/styles/VirtualMessage.scss

When updated from div to button, the border and background styles of the message actions option changed.

fix: remove button styles from message actions option

---

src/styles/Message.scss
src/styles/VirtualMessage.scss

Introduces an utility class for the default message component that allows temporary highlight of a message. 
Useful when jumping to a message.

feat: class for highlighted messages

---

src/styles/Message.scss

This is an Angular only change
Before:
After:

fix: Read by count in Angular SDK

---

docs/theming/component-variables.mdx
src/v1/MessageInputFlat.scss
src/v1/SendButton.scss
src/v2/styles/AttachmentPreviewList/AttachmentPreviewList-layout.scss
src/v2/styles/AttachmentPreviewList/AttachmentPreviewList-theme.scss
src/v2/styles/Channel/Channel-layout.scss
src/v2/styles/Channel/Channel-theme.scss
src/v2/styles/MessageInput/MessageInput-layout.scss
src/v2/styles/MessageInput/MessageInput-theme.scss
src/v2/styles/_theme-variables.scss
src/v2/styles/index.layout.scss
src/v2/styles/index.scss
src/vendor/react-file-utils.scss

Details: https://github.com/GetStream/stream-chat-angular/pull/297

feat: Message input - theme-v2 #93

---

docs/theming/component-variables.mdx
src/v2/styles/Autocomplete/Autocomplete-layout.scss
src/v2/styles/Autocomplete/Autocomplete-theme.scss
src/v2/styles/MessageInput/MessageInput-layout.scss
src/v2/styles/MessageInput/MessageInput-theme.scss
src/v2/styles/_theme-variables.scss
src/v2/styles/_utils.scss
src/v2/styles/index.layout.scss
src/v2/styles/index.scss

Second part of the message input implementation
closes #93

feat: Message input theme-v2 missing features #93

---

src/styles/MessageActions.scss
src/styles/Modal.scss
src/styles/_variables.scss

The PR includes styling for the buttons the UI displays when a message fails our moderation filters.
It also fixes the abysmally small message edit box.

Styling for NNBB related elements

---

src/v2/styles/AttachmentList/AttachmentList-layout.scss
src/v2/styles/AttachmentPreviewList/AttachmentPreviewList-layout.scss
src/v2/styles/ChannelPreview/ChannelPreview-layout.scss
src/v2/styles/Message/Message-layout.scss
src/v2/styles/MessageInput/MessageInput-layout.scss
src/v2/styles/_utils.scss

Safari and Firefox test fixes (also tested in Opera)

fix: Browser testing bugs

---

docs/theming/component-variables.mdx
docs/theming/theme-variables.mdx
src/v1/Attachment.scss
src/v2/styles/AttachmentList/AttachmentList-layout.scss
src/v2/styles/AttachmentList/AttachmentList-theme.scss
src/v2/styles/Channel/Channel-theme.scss
src/v2/styles/Message/Message-layout.scss
src/v2/styles/Message/Message-theme.scss
src/v2/styles/Thread/Thread-layout.scss
src/v2/styles/_theme-variables.scss
src/v2/styles/_utils.scss

fix: Design enhancements

---

docs/theming/component-variables.mdx
src/v2/styles/EditMessageForm/EditMessageForm-layout.scss
src/v2/styles/EditMessageForm/EditMessageForm-theme.scss
src/v2/styles/ImageCarousel/ImageCarousel-layout.scss
src/v2/styles/ImageCarousel/ImageCarousel-theme.scss
src/v2/styles/Message/Message-layout.scss
src/v2/styles/Message/Message-theme.scss
src/v2/styles/Modal/Modal-layout.scss
src/v2/styles/Modal/Modal-theme.scss
src/v2/styles/_theme-variables.scss
src/v2/styles/index.layout.scss
src/v2/styles/index.scss

https://github.com/GetStream/stream-chat-angular/pull/312
closes #97

feat: Modal component theme-v2 #97

---

src/v2/styles/MessageList/MessageList-layout.scss
src/v2/styles/Thread/Thread-theme.scss

Based on https://getstream.slack.com/archives/C012FGW0XJS/p1655813378953279

fix: Thread layout - message input position

---

src/v2/styles/AttachmentPreviewList/AttachmentPreviewList-layout.scss
src/v2/styles/Autocomplete/Autocomplete-layout.scss
src/v2/styles/Autocomplete/Autocomplete-theme.scss
src/v2/styles/LoadingIndicator/LoadingIndicator-theme.scss
src/v2/styles/MessageInput/MessageInput-layout.scss
src/v2/styles/Modal/Modal-layout.scss
src/v2/styles/_utils.scss
src/v2/styles/index.scss
src/v2/styles/vendor/emoji-mart.scss

ThemingV2: MessageInput component styling

---

docs/theming/SDKSpecific.jsx
src/v2/styles/MessageList/VirtualMessageList-theme.scss
src/v2/styles/_utils.scss

Some miscellaneous items I found during preparing for the theming blog post

Custiomization example fixes

---

src/v2/styles/AttachmentPreviewList/AttachmentPreviewList-layout.scss
src/v2/styles/AttachmentPreviewList/AttachmentPreviewList-theme.scss
src/v2/styles/Message/Message-layout.scss
src/v2/styles/Message/Message-theme.scss
src/v2/styles/MessageInput/MessageInput-layout.scss
src/v2/styles/MessageList/MessageList-layout.scss
src/v2/styles/MessageList/MessageList-theme.scss
src/v2/styles/Thread/Thread-layout.scss
src/v2/styles/_utils.scss

Few small changes to make the UI look more consistent. Mostly affecting the thread header.

Theming2 touchups

---

src/v2/styles/Message/Message-layout.scss

fix: Word break inside the message component

---

package.json

Creating a prerelease for testing purposes
- The release will be created from `theming2` branch
- Turned on dry run to check the release notes and version before the actual prerelease
- Created an empty commit to trigger a breaking change and increase the version from 2 -> 3

Prerelease for theming2

---

src/v2/styles/AttachmentList/AttachmentList-layout.scss
src/v2/styles/ChannelPreview/ChannelPreview-theme.scss
src/v2/styles/_utils.scss

Fixes to be added to the main user testing branch for Theming V2 (React)

Theming2 user testing react

---

src/styles/Message.scss

feat: Disable attachments interactions on quoted messages

---

src/v1/MessageInput.scss
src/v2/styles/Message/Message-layout.scss

Angular latest test fixes

---

src/styles/Gallery.scss

This makes Angular compatible with the latest version of stream-chat-css

fix: Angular image modal width

---

src/styles/Message.scss
src/styles/MessageList.scss

Disable attachment actions for quoted messages

---

src/v1/Attachment.scss
src/v1/Gallery.scss
src/v1/Message.scss
src/v2/styles/AttachmentList/AttachmentList-layout.scss

Integrate new CDN capabilities to stream-chat-angular
- Previously stream-chat-angular used fixed height for videos, with the new CDN capabilities this is a problem, the fixed height is left in the source code because stream-chat-react still needs it.
- The new image/video sizing requires `height`/`max-height` and `max-width` to be set on host HTML elements of images and videos

New CDN integration - Angular

---

src/v2/styles/index.scss
src/v2/styles/vendor/react-image-gallery.scss

Fix the react-image-gallery reference in the v2/index.scss file. Current path does not point to an existing file in the React SDK bundle.

fix: provide react-image-gallery styles to v2 in local vendor folder

---

src/v1/Attachment.scss
src/v2/styles/AttachmentList/AttachmentList-layout.scss

feat: Integrate new CDN features with stream-chat-react

---

src/v2/styles/index.scss
src/v2/styles/vendor/react-image-gallery.scss

CDN integration for stream-chat-react

---

src/v1/Message.scss
src/v2/styles/Message/Message-layout.scss
src/v2/styles/Message/Message-theme.scss

feat: Auto translation for Angular SDK

---

src/v1/Attachment.scss
src/v1/Message.scss
src/v2/styles/AttachmentList/AttachmentList-layout.scss
src/v2/styles/_utils.scss

feat: calculate attachment height in CSS

---

.github/workflows/workflow.yml
scripts/parser.ts

Calc attachment height in css

---

.github/workflows/workflow.yml
package.json
src/v1/Attachment.scss
src/v1/Message.scss
src/v1/MessageCommerce.scss
src/v1/Thread.scss
src/v1/VirtualMessage.scss

release v3.1.2

---

src/v1/Attachment.scss
src/v2/styles/AttachmentList/AttachmentList-layout.scss
src/v2/styles/_utils.scss

fix: landscape video height in theme-v1

---

docs/theming/_category_.json

Made room for both in react and angular docs.
https://github.com/GetStream/stream-chat-react/pull/1794 https://github.com/GetStream/stream-chat-angular/pull/391

Move the theming up to position 2.

---

src/v2/styles/Message/Message-theme.scss

feat: Make own message bubble text color configurable

---

src/v2/styles/AttachmentList/AttachmentList-layout.scss

Fixes: https://github.com/GetStream/stream-chat-react/issues/1849

fix: add immediate-child selector to prevent gallery targeting

---

src/v2/styles/Message/Message-layout.scss

https://www.loom.com/share/a44697150de34e7d8dcddeeb1c5fa3aa 
Changes only affect the Angular SDK, not React.
Angular implementation for reference: https://github.com/GetStream/stream-chat-angular/commit/8d43dfa897c58d5af226e9a41d3616346287fc85

feat: Message options can be triggered only by click/hover inside bubble

---

src/v2/styles/Message/Message-layout.scss
src/v2/styles/MessageList/MessageList-layout.scss

Message options trigger

---

.github/PULL_REQUEST_TEMPLATE.md
src/v2/styles/Message/Message-layout.scss

fix: Message options doesn't appear in virtualized message list

---

src/v1/_variables.scss
src/v2/styles/_emoji-replacement.scss

Allow integrators to override the assets location when generating own bundle.

feat: allow to override $assetsPath sass variable

---

.github/workflows/workflow.yml

Update release flow to use built-in GITHUB TOKEN instead of PAT

---

src/v2/styles/Autocomplete/Autocomplete-layout.scss
src/v2/styles/LinkPreview/LinkPreview-layout.scss
src/v2/styles/LinkPreview/LinkPreview-theme.scss
src/v2/styles/LinkPreview/index.scss
src/v2/styles/index.layout.scss
src/v2/styles/index.scss

Add styles for link preview in message input.

feat: add styles for link previews

---

src/v2/styles/MessageList/MessageList-layout.scss
src/v2/styles/MessageList/VirtualizedMessageList-layout.scss

fixes https://github.com/GetStream/stream-chat-react/issues/2164

fix(react-sdk): prevent blank message list on fast scroll in iOS browsers

---

src/v2/styles/Notification/Notification-layout.scss

Fixes https://github.com/GetStream/stream-chat-react/issues/2160

fix: lift the notification banner above the modal overlay

---

src/v2/styles/AttachmentPreviewList/AttachmentPreviewList-layout.scss
src/v2/styles/Message/Message-layout.scss
src/v2/styles/Message/Message-theme.scss
src/v2/styles/_global-theme-variables.scss

Provide styles for 
1. separator of unread messages in message list
2. floating notification about unread messages

feat: add styles for unread messages separator and notification

---

src/v2/styles/Message/Message-layout.scss
src/v2/styles/_base.scss

Angular-only changes to fix glitches around popper menus

fix(angular): popper styles

---

src/v2/styles/MessageReactions/MessageReactions-layout.scss

Quick stylint violation fix after #270.

fix: stylelint violatiom

---

src/v2/styles/_base.scss

fix(angular): message actions menu arrow sometimes appears

---

src/v1/Message.scss
src/v1/MessageActions.scss
src/v1/_base.scss
src/v2/styles/EditMessageForm/EditMessageForm-layout.scss
src/v2/styles/Message/Message-layout.scss
src/v2/styles/MessageActionsBox/MessageActionsBox-layout.scss

- React + Angular: Hide unstyled UI components related to mark unread in theme-v1
- Angular: Hide unstyled UI components related to message bounce flow in theme-v1
- Angular: CSS update after edit message modal was moved up in DOM tree - theme-v1 + theme-v2
- Code reformats :( 

Message bounce angular

---

src/v2/styles/Message/Message-layout.scss

fix: typo in timestamp class name

---

src/v2/styles/_base.scss

feat(angular): add styles for ngx-floax-ui

---

src/v2/styles/AttachmentList/AttachmentList-layout.scss

- fix https://github.com/GetStream/stream-chat-react/issues/2318

fix: remove play button z-index

---

src/v2/styles/AttachmentList/AttachmentList-layout.scss
src/v2/styles/AttachmentList/AttachmentList-theme.scss
src/v2/styles/AttachmentPreviewList/AttachmentPreviewList-layout.scss
src/v2/styles/AttachmentPreviewList/AttachmentPreviewList-theme.scss
src/v2/styles/AudioRecorder/AudioRecorder-layout.scss
src/v2/styles/AudioRecorder/AudioRecorder-theme.scss
src/v2/styles/MessageInput/MessageInput-layout.scss
src/v2/styles/MessageInput/MessageInput-theme.scss
src/v2/styles/index.layout.scss
src/v2/styles/index.scss

Provide styles for audio recorder UI.
https://github.com/GetStream/stream-chat-react/pull/2339

feat: add audio recording styles

---

src/v2/styles/Message/Message-layout.scss
src/v2/styles/MessageReactions/MessageReactionsSelector-layout.scss
src/v2/styles/MessageReactions/MessageReactionsSelector-theme.scss

Details: https://getstream.slack.com/archives/C06CF5TKRGA/p1718615543296159

feat: angular message menu UI refactor

---

src/v2/styles/MessageReactions/MessageReactionsSelector-layout.scss
src/v2/styles/_base.scss

fix(angular): v5 small fixes

---

src/v2/styles/Avatar/Avatar-layout.scss
src/v2/styles/Avatar/Avatar-theme.scss
src/v2/styles/ChatView/ChatView-layout.scss
src/v2/styles/ChatView/ChatView-theme.scss
src/v2/styles/MessageList/MessageList-layout.scss
src/v2/styles/MessageList/VirtualizedMessageList-layout.scss
src/v2/styles/Thread/Thread-layout.scss
src/v2/styles/ThreadList/ThreadList-layout.scss
src/v2/styles/ThreadList/ThreadList-theme.scss
src/v2/styles/UnreadCountBadge/UnreadCountBadge-layout.scss
src/v2/styles/UnreadCountBadge/UnreadCountBadge-theme.scss
src/v2/styles/index.layout.scss
src/v2/styles/index.scss

Introduces styling for the new threads 2.0 related components.

feat: threads 2.0 styling

---

src/v2/styles/_base.scss

This PR only affects the Angular SDK. As part of reactions-v2 I created two, lightweight (in terms of CSS) components:
- Paginated list
- User list
This PR contains the CSS for those.

feat(angular): paginated list component

---

src/v2/styles/ChannelList/ChannelList-layout.scss
src/v2/styles/_base.scss

fix(angular): channel list infinite scroll

---

src/v2/styles/ChannelList/ChannelList-layout.scss

fix(angular): remove gap from channel list

---

src/v2/styles/Avatar/Avatar-layout.scss
src/v2/styles/Avatar/Avatar-theme.scss

Styles for https://github.com/GetStream/stream-chat-react/pull/2556

feat: add group avatar styles

---

src/v2/styles/ChannelPreview/ChannelPreview-layout.scss
src/v2/styles/ChannelPreview/ChannelPreview-theme.scss

Adds styling for the channel pinning and archiving feature.

feat: add styling for channel pinning and archiving feature

---

package.json
src/v2/styles/Channel/Channel-layout.scss
src/v2/styles/vendor/react-image-gallery.scss
yarn.lock

https://getstream.slack.com/archives/C05GR3S04E8/p1740480279057069

fix: upgrade SASS and adjust rules accordingly

---

src/v2/styles/Message/Message-layout.scss
src/v2/styles/Message/Message-theme.scss

Adds styling for MessageBlocked component.
Ref: https://github.com/GetStream/stream-chat-react/pull/2675

feat: add styling for MessageBlocked component

---

src/v2/styles/MessageInput/MessageInput-layout.scss

Closes: REACT-368
**Before**
---------------------------
**After**

fix: prevent quoted poll text overflow with ellipsis

---

src/v2/styles/AttachmentPreviewList/AttachmentPreviewList-layout.scss

fix: elevate remove attachment preview button to allow removal of failed upload attachments
